### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by 4ifi** [RaghuVarma331/android_device_samsung_m21-TWRP#1]
1 warning generated.
[ 91% 18127/19907] Target buildinfo: /home/user/m21-recovery/twrp/out/target/pr
Target buildinfo from: device/samsung/m21/system.prop
[ 98% 19555/19907] Install: /home/user/m21-recovery/twrp/out/target/product/m21
FAILED: /home/user/m21-recovery/twrp/out/target/product/m21/recovery/root/twrp_ramdisk-timestamp
/bin/bash -c "(rm -f /home/user/m21-recovery/twrp/out/target/product/m21/recovery/root/twrp_ramdisk-timestamp ) && (cp /home/user/m21-recovery/twrp/out/target/product/m21/obj/FAKE/twrp_ramdisk_intermediates/twrp_ramdisk-timestamp /home/user/m21-recovery/twrp/out/target/product/m21/recovery/root/twrp_ramdisk-timestamp ) && (mkdir -p /home/user/m21-recovery/twrp/out/target/product/m21/recovery/root/sbin; ln -sf /system/bin/sh /home/user/m21-recovery/twrp/out/target/product/m21/recovery/root/sbin/sh && mkdir -p /home/user/m21-recovery/twrp/out/target/product/m21/recovery/root/system/etc/selinux/ && cp /home/user/m21-recovery/twrp/out/target/product/m21/root/../system/etc/selinux/plat_service_contexts /home/user/m21-recovery/twrp/out/target/product/m21/recovery/root/system/etc/selinux/plat_service_contexts && cp /home/user/m21-recovery/twrp/out/target/product/m21/root/../system/etc/selinux/plat_hwservice_contexts /home/user/m21-recovery/twrp/out/target/product/m21/recovery/root/system/etc/selinux/plat_hwservice_contexts && cp /home/user/m21-recovery/twrp/out/target/product/m21/root/../vendor/etc/selinux/vndservice_contexts /home/user/m21-recovery/twrp/out/target/product/m21/recovery/root/system/etc/selinux/vndservice_contexts && cp /home/user/m21-recovery/twrp/out/target/product/m21/root/../vendor/etc/selinux/vendor_hwservice_contexts /home/user/m21-recovery/twrp/out/target/product/m21/recovery/root/system/etc/selinux/vendor_hwservice_contexts )"
cp: bad '/home/user/m21-recovery/twrp/out/target/product/m21/root/../system/etc/selinux/plat_hwservice_contexts': No such file or directory
[ 98% 19558/19907] //libcore/mmodules/core_platform_api:core-platform-api-stubs

/home/user/m21-recovery/twrp/external/bouncycastle/repackaged/bcprov/src/main/java/com/android/org/bouncycastle/asn1/x500/style/BCStyle.java:17: warning: Public class com.android.org.bouncycastle.asn1.x500.style.BCStyle stripped of unavailable superclass com.android.org.bouncycastle.asn1.x500.style.AbstractX500NameStyle [HiddenSuperclass]
20:17:10 ninja failed with: exit status 1

#### failed to build some targets (24:33 (mm:ss)) ####

mv: cannot stat 'recovery.img': No such file or directory

**Comment by RaghuVarma331** [comment]
resolved now. sources updated please follow readme.txt
