### ISSUE TITLE
stuck on twrp logo

### ISSUE THREAD

**Issue by 4ifi** [RaghuVarma331/android_device_samsung_m21-TWRP#2]
stuck on twrp logo but adb shell works
dmesg: https://del.dog/cimabirije

**Comment by RaghuVarma331** [comment]
will look but working fine for me :) i already released here 
https://forum.xda-developers.com/galaxy-m21/development/unofficial-twrp-3-4-0-0-team-win-t4185397

**Comment by 4ifi** [comment]
downloaded your build and got same issue

**Comment by 4ifi** [comment]
[recovery.log](https://github.com/RaghuVarma331/android_device_samsung_m21-TWRP/files/5501364/recovery.log)
Check my log please

**Comment by 4ifi** [comment]
I have one idea, just wait

**Comment by RaghuVarma331** [comment]
> I have one idea, just wait

Hi please text me in telegram @RaghuVarma

**Comment by 4ifi** [comment]
@RaghuVarma331 forked your repo and wrote fix for GSI!
https://github.com/4ifi/android_device_samsung_m21-TWRP
